version: "3.8"
services:
  n8n:
    image: n8n:latest
    env_file:
      - ./tiktok-workflow/.env
    ports:
      - "5678:5678"
    depends_on:
      - redis

  redis:
    image: redis:alpine

  render:
    build:
      context: ./tiktok-workflow
      dockerfile: Dockerfile
    env_file:
      - ./tiktok-workflow/.env
