# .github/workflows/deploy.yml
name: Déployer sur Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) On récupère le code du dépôt
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2) On installe Railway CLI
      - name: Installer Railway CLI
        run: npm install -g @railway/cli

      # 3) Connexion non-interactive à Railway avec le token
      - name: Connexion à Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --token "$RAILWAY_TOKEN"

      # 4) Lier ton dossier à ton projet/env/service Railway
      - name: Lier le projet Railway
        run: |
          railway link \
            --project ${{ secrets.RAILWAY_PROJECT_ID }} \
            --environment production \
            --service Projet-TikTok-Viral-Remix

      # 5) Déployer tous les services définis dans docker-compose.yml
      - name: Déployer les services
        run: railway up --service all --detach
