# .github/workflows/deploy.yml
name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) On récupère le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) On déploie avec l’action Railway
      - name: Railway deploy
        uses: railwayapp/github-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          projectId:    ${{ secrets.RAILWAY_PROJECT_ID }}
          environment:  production         # ou staging selon ton setup
          service:      Projet-TikTok-Viral-Remix
          detach:       true               # pour lancer en background
