# .github/workflows/deploy.yml
name: Déployer sur Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2) Installer Railway CLI
      - name: Installer Railway CLI
        run: npm install -g @railway/cli

      # 3) Connexion non interactive à Railway
      - name: Connexion à Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login

      # 4) Lier projet / env / service
      - name: Lier le projet Railway
        run: |
          railway link \
            --project ${{ secrets.RAILWAY_PROJECT_ID }} \
            --environment production \
            --service Projet-TikTok-Viral-Remix

      # 5) Déployer compose
      - name: Déployer les services
        run: railway up --service all --detach
